/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BJumbotron: typeof import('./src/components/BJumbotron.vue')['default']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BOrchestrator: typeof import('bootstrap-vue-next/components/BApp')['BOrchestrator']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    ContactForm: typeof import('./src/components/contact/ContactForm.vue')['default']
    EventItem: typeof import('./src/components/EventItem.vue')['default']
    EventList: typeof import('./src/components/EventList.vue')['default']
    FeatureList: typeof import('./src/components/FeatureList.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    IBiLink45: typeof import('~icons/bi/link45')['default']
    IBiLink45deg: typeof import('~icons/bi/link45deg')['default']
    MetricCard: typeof import('./src/components/metric/MetricCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NotificationList: typeof import('./src/components/notification/NotificationList.vue')['default']
    PinInput: typeof import('./src/components/PinInput.vue')['default']
    PinRequestForm: typeof import('./src/components/contact/PinRequestForm.vue')['default']
    PreparationSection: typeof import('./src/components/request/PreparationSection.vue')['default']
    RequestForm: typeof import('./src/components/request/RequestForm.vue')['default']
    RequirementsSection: typeof import('./src/components/request/RequirementsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StreamingContact: typeof import('./src/components/StreamingContact.vue')['default']
    StreamingNotes: typeof import('./src/components/StreamingNotes.vue')['default']
    StreamItem: typeof import('./src/components/stream/StreamItem.vue')['default']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
